# Generated by Django 4.1.1 on 2024-05-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
